### ISSUE TITLE
How to get the content of UBX-RXM-RTCM?

### ISSUE THREAD

**Issue by shubham9436** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#104]
I am using `pushRawdata` function to push RTCM data. I am using rtk2go as our caster, so hopefully the data would be valid.

`pushRawdata` returns true if all data bytes are pushed successfully. Still, I am not able to figure it out like what is the indication that it is using Correction data. I know there is a parameter named as `UBX-RXM-RTCM` through which we can get the status.

**Comment by PaulZC** [comment]
Hi Shubham (@shubham9436 ),

If you are using one of our ZED-F9x boards, you can plug in a USB cable and use u-center to monitor the UBX-MON-COMMS message. It will show you how many RTCM messages have been received and processed.

Our library does not support UBX-MON-COMMS or UBX-RXM-RTCM directly, but you could read them with a custom packet and then parse the data yourself. [Example21](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/main/examples/Example21_ModuleInfo/Example21_ModuleInfo.ino) is a good place to start.

Best wishes,
Paul
