### ISSUE TITLE
Add note in readme.md that lib can not work with ublox M6 modules

### ISSUE THREAD

**Issue by cyberman54** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#106]
It should maybe mentioned in the readme.md, that this library is getting the positioning data from UBX message `UBX-NAV-PVT`, and thus can NOT work with older ublox M6 modules, which do not send this UBX message.

**Comment by PaulZC** [comment]
Hi Verkehrsrot (@cyberman54),

OK. Fair enough. Added [here](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#compatibility).

Best wishes,
Paul
