### ISSUE TITLE
Help wanted: Possible to use library for single camera capture?

### ISSUE THREAD

**Issue by dderosa1** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#108]
I am interested in the Sparkfun GNSS module in order to synchronize camera capture. Would it be possible to use this to send a single signal through TIMEPULSE?

**Comment by PaulZC** [comment]
Hi @dderosa1 ,

There are examples showing how to configure the Time Pulse here:
https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/tree/main/examples/Example23_TimePulseParameters

Best wishes,
Paul
