### ISSUE TITLE
'class SFE_UBLOX_GNSS' has no member named 'getLatestNMEA.....'

### ISSUE THREAD

**Issue by cambut** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#123]
When compiling Example1_getLatestNMEAGPGGA on Arduino IDE 1.8.16 the following error is thrown

Example1_getLatestNMEAGPGGA:103:19: error: 'class SFE_UBLOX_GNSS' has no member named 'getLatestNMEAGNGGA'

Looking through the "keywords.txt" file, this member should exist

Can you confirm if this library is intended to compile on Arduino IDE?

**Comment by PaulZC** [comment]
Hi Cameron (@cambut ),

Please see [the release notes for v2.2.3](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/releases/tag/v2.2.3). The library is now too large to fit into the Uno (ATmega328) program memory. I can make it fit - just - but only by disabling the auto-NMEA support.

A couple of options for you:

* Use v2.2.2. That supports auto-GGA (only). Example1_getLatestNMEAGPGGA does compile.

![image](https://user-images.githubusercontent.com/5690545/156532390-b6442c1f-528f-4821-ab82-72c15aeed770.png)

* If you are using an ATmega2560 or ATmega1280, those do have enough memory. If you comment this line out, the code will compile:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/f324b40f274796db593173ee31f67998955bd53c/src/SparkFun_u-blox_GNSS_Arduino_Library.h#L64

I will add an extra check for the mega to let it compile automatically. I'll also make it clearer in the README what the memory requirements / limitations are.

Best wishes,
Paul
