### ISSUE TITLE
can this repo work with sparkfun zed F9K?

### ISSUE THREAD

**Issue by ideafold** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#134]
can this repo work with sparkfun zed F9K?
Thanks.

**Comment by PaulZC** [comment]
Hi @ideafold ,

Yes, it will. The basic interface is the same as the ZED-F9P / ZED-F9R.

However, there may be some messages specific to the ZED-F9K (u-blox F9 LAP 1.20) which the library does not support directly. If you see any, please raise a new issue requesting them to be added.

Best wishes,
Paul
