### ISSUE TITLE
HELP Can you tell me about connection GPS/GNSS with arduino 

### ISSUE THREAD

**Issue by kamon2022** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#141]
I use this sensor using arduino mega 2560 and arduino NANO.

Could you explain me about connection this sensor with arduino board ?

For example, Tx of GPS connect pin D1 of arduino.

**Comment by PaulZC** [comment]
Hello @kamon2022 ,

The best place to ask questions like this is in our [GPS Forum](https://forum.sparkfun.com/viewforum.php?f=116).

Please be careful. The MEGA 2560 is a 5V board. All of our u-blox GNSS boards are 3.3V. You must use 5V to 3.3V level-shifters when connecting a 5V microcontroller to a 3.3V GNSS board.

Best wishes,
Paul
