### ISSUE TITLE
Add polling exemple of RXM RAWX and SFRBX

### ISSUE THREAD

**Issue by Gabrowsk** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#149]
### Subject of the issue
I would like to see an exemple of data logging RXM RAWX and SFRBX that isnt automatic.

### Your workbench
* What development board or microcontroller are you using?
* What version of hardware or breakout board are you using? 
* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by PaulZC** [comment]
Hi @Gabrowsk ,

It is possible to poll RAWX, but not SFRBX. SFRBX is output only.

Also, the data logging functionality in the library depends on the messages arriving 'automatically' (periodically).

So, with apologies, I'm not able to provide a polling example.

Best wishes,
Paul
