### ISSUE TITLE
how to config DATUM parameters?

### ISSUE THREAD

**Issue by Gabrowsk** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#151]
### Subject of the issue
More like a question.
Is there a way to set my own DATUM parameters?
I live in Brazil, and our datum here is called SIRGAS2000, but I  didnt find it in the DATUM config on ucenter, and I am trying to use zed-f9p with esp32. So I need to manually config this.

Thanks, 
Gabriel.
### Your workbench
* ESP32 and SparkFun GPS-RTK2 Board - ZED-F9P
* What version of hardware or breakout board are you using? 
* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by PaulZC** [comment]
Hi Gabriel (@Gabrowsk ),

It might be better to ask this question in the GPS Forum. I know we have customers in South America who are active on that Forum. They may be able to answer your question better than I can.

https://forum.sparkfun.com/viewforum.php?f=116

It is possible to set a user-defined datum using the UBX-CFG-DAT message:

![image](https://user-images.githubusercontent.com/5690545/185572945-63ead823-f57b-412d-bb09-b702b41ac700.png)

Do you have the axis, shift and rotation values for SIRGAS2000? If you do, you can enter then through u-center:

![image](https://user-images.githubusercontent.com/5690545/185573823-bbcee0a6-469f-455b-985b-af5ef81dfc10.png)

Best wishes,
Paul
