### ISSUE TITLE
library.properties formatting and search issues with Arduino IDE 2.0 Library Manager

### ISSUE THREAD

**Issue by jh83** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#154]
### Subject of the issue
When searching for the "SparkFun_u-blox_GNSS_Arduino_Library" in the new Arduino IDE 2.0, only the old "SparkFunk u-blox arduino library" version 1.8.11 is returned.

Can you help with adding the SparkFun_u-blox_GNSS_Arduino_Library library so that it is visible in the Arduino IDE 2.0 library manager?

### Your workbench
Windows 10

### Steps to reproduce
Install Arduino IDE 2.0.
Go to library manager and search for SparkFun_u-blox_GNSS_Arduino_Library
One result is shown, but this result is the old version and not the up-to-date package.

### Expected behavior
Same results as in the "old" Arduino IDE in which the latest version of the SparkFun_u-blox_GNSS_Arduino_Library is visible

### Actual behavior
An old version of the SparkFun_u-blox_GNSS_Arduino_Library library is displayed.
![image](https://user-images.githubusercontent.com/16517831/190338647-a281059d-fad7-4cb2-b3af-4c1984b7c903.png)

**Comment by PaulZC** [comment]
Hi @jh83 ,

Thanks for reporting this.

It looks like the library manager search tool is slightly different in v2.

If I search for "SparkFun u-blox GNSS" (with spaces) I see both the old and new libraries:

![image](https://user-images.githubusercontent.com/5690545/190424586-434fcf7a-ff0a-47ed-814b-1e9dc47197c3.png)

If I search for "SparkFun_u-blox_GNSS" (with underscores) I only see the old library:

![image](https://user-images.githubusercontent.com/5690545/190424889-d5d2a838-6243-4aa5-a03d-57378fef2ccc.png)

What's more worrying is this:

With Arduino IDE 1.8, you could include hyperlinks in examples which would automatically open the library manager:

```
//Click here to get the library: http://librarymanager/All#SparkFun_u-blox_GNSS
```

With v2, those links open in a web browser and fail as they are not correctly formatted HTTP...:

![image](https://user-images.githubusercontent.com/5690545/190426534-396d0d71-7cb8-4a11-8efc-f7ce0b39574d.png)

OK. Thanks again for reporting. The answer to your particular issue is to search using spaces, not underscores. But it is clear we have other issues to solve with v2...

Best wishes,
Paul

**Comment by PaulZC** [comment]
Submitted as an issue here:

https://github.com/arduino/arduino-ide/issues/1442

**Comment by PaulZC** [comment]
Hi @jh83 ,

Arduino have fixed this issue. Please see the above link for full details. They have not yet released the changes, but it is fixed in the most recent "nightly build":

https://www.arduino.cc/en/software

Thanks again for the heads-up.

Closing...

Best wishes,
Paul
