### ISSUE TITLE
Does the MAX-M10S support geofence ?

### ISSUE THREAD

**Issue by JimKruk** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#170]
I saw sparkfun sells this Gnss receiver SparkFun GNSS Receiver Breakout - MAX-M10S (Qwiic) GPS-18037 and the doc points to this library.  Does that device support geofence, specifically Example17_Geofence.ino ?
Thanks

**Comment by PaulZC** [comment]
Hi @JimKruk ,

Looking at the [M10 interface description](https://www.u-blox.com/sites/default/files/u-blox-M10-SPG-5.10_InterfaceDescription_UBX-21035062.pdf), I don't see any mention of UBX-CFG-GEOFENCE or the associated Configuration Keys. So, unfortunately, no. It isn't supported.

Best wishes,
Paul
