### ISSUE TITLE
I would like to get the magnetometer values.

### ISSUE THREAD

**Issue by jinhyeongRepo** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#180]
### Subject of the issue
https://cdn.sparkfun.com/assets/learn_tutorials/1/1/7/2/ZED-F9R_Interfacedescription__UBX-19056845_.pdf
![image](https://user-images.githubusercontent.com/101238677/216981069-361f703c-b483-4d4f-8ddd-9ecfc29114b5.png)
![image](https://user-images.githubusercontent.com/101238677/216981176-cda5f6b6-9905-46ea-ac98-2c5576ad87c4.png)
![image](https://user-images.githubusercontent.com/101238677/216981484-5fccc12c-b175-4be8-99c6-be636125f02e.png)

I thought I could get the magnetometer value from ZED-F9R by checking the datasheet.
Therefore, I tried to obtain the magnetometer value using the example provided (CallbackExample10_ESF_RAW).
In this example, I checked the value "ubxDataStruct->data[i].data.bits.dataType" and found that only values between 0 and 18 were displayed (I expected values between 0 and 25).
But this range does not contain data about the magnetometer.
Is there any other way to get the magnetometer value?

### Your workbench
I have updated the firmware to version 1.30 and am using an ESP32 with the ZED-F9R for testing purposes (I2C).

### Steps to reproduce & Actual behavior
After checking the "CallbackExample10_ESF_RAW" example from the SparkFun u-blox GNSS Arduino Library (https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/a7097c8257f87b6b6ce65048baba706d6e2af7c7/examples/Callbacks/CallbackExample10_ESF_RAW/CallbackExample10_ESF_RAW.ino), I was unable to find any values with datatype 22, 23, or 24. This means that I was unable to retrieve the magnetometer values.

### Expected behavior
I expected "ubxDataStructure->data[i].data.bits.dataType" to have a value from 0 to 25, so I want to get the value of the magnetometer.

**Comment by PaulZC** [comment]
Hi jinhyeong (@jinhyeongRepo ),

The F9R does not have a built-in magnetometer. I believe it is only possible to to read this data if you connect an **external** magnetometer.

Best wishes,
Paul
