### ISSUE TITLE
Note that the MSL model is a gridded EGM96 geoid

### ISSUE THREAD

**Issue by drf5n** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#182]
Here the code has a couple references to the MSL model:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/2ae72895a1194c77e0628d50ec51937016ac7466/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp#L17402-L17405

It should also refer to uBlox at 

https://portal.u-blox.com/s/question/0D52p00008HKDSkCAP/what-geoid-model-is-used-and-where-is-this-calculated
...which seems to indicate EGM96 on a 10°x10° grid, interpolated to the location.

Maybe add a line like:

    // Geoid: https://cddis.nasa.gov/926/egm96/egm96.html on 10x10 degree grid

**Comment by PaulZC** [comment]
Hi @drf5n ,

Thanks! We'll add this to the next release.

Best wishes,
Paul
