### ISSUE TITLE
GPS Accuracy and Constallations

### ISSUE THREAD

**Issue by jan5650** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#192]
Respected!

I use the M8N GPS module.

I have a question: what happens if I enable 3 installations (GPS, GLONASS, GALILEO) but my external antenna does not support only GPS/GLONASS? The fact that Galileo is activated but I have nothing to receive with does not cause a problem or inaccuracy? Funnily enough if I turn it off I only get 10-12 satellites between houses, if I turn Galileo on I get 14-15, even though the antenna does not support Galileo. Why is that?

Currently I store the LATitude/LONgtitude values in LONG type. Is there a more precise type that I should use? Int_32, etc? If so, how should I declare it, use it and is it of any practical use? I used to store it in float, now I store it in long for a while, question if there is a better way.

Thank you Guys!

**Comment by PaulZC** [comment]
Hi @jan5650 ,

The frequency of the Galileo E1 signals is almost the same as the GPS L1 signals. Even though your antenna says it does not support Galileo, it will still be receiving a signal:

https://gssc.esa.int/navipedia/index.php/File:GNSS_navigational_frequency_bands.png

The u-blox modules return latitude as a signed 32-bit number (```int32_t```) containing degrees * 10^-7 (seven decimal places). On most platforms, ```long``` is the same as ```int32_t```. Storing it as ```float``` is OK but may restrict the resolution. On most platforms, ```float``` is 32-bit and will provide seven significant digits - which can be different to seven decimal places. You can use ```double``` instead - which is usually 64-bit.

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/3416a3140fb74c3b80fc680140d029182fcd03ad/src/SparkFun_u-blox_GNSS_Arduino_Library.h#L1405

Best wishes,
Paul
