### ISSUE TITLE
Using ZOE-M8Q with active antenna

### ISSUE THREAD

**Issue by Savaesc** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#194]
Hello,

I am trying to use the ZOE-M8Q with an active antenna such as M20057-1. How do i configure the ZOE-M8Q to work with an active antenna? I couldn't find any command or documentation about this problem, so i hope someone can help me out. 

Thanks!

**Comment by PaulZC** [comment]
Hi @Savaesc ,

The best place to ask questions like this is the GPS Forum: https://forum.sparkfun.com/viewforum.php?f=116

If you have one of our ZOE-M8Q breakouts ( https://www.sparkfun.com/products/15193 ), it provides 3.3V for an active antenna via the u.FL connector.

The M20057-1 has pads on the bottom which you solder connections to. It is designed to be soldered onto a circuit board. To use it with our breakout, you will need to strip the end of a u.FL cable, separate the coax braid and core, solder the braid to one of the GND pads, and solder the core to the RFO/VCC pad.

The M20057-1 datasheet shows a resistor and an inductor connected to the two tuning pads. I do not know how essential those are. It may work without them, or they may be required for correct operation. I do not know.

Best wishes,
Paul
