### ISSUE TITLE
Power Save Mode on NEO-M9N

### ISSUE THREAD

**Issue by caioorafael** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#195]
### Subject of the issue
Describe your issue here. If you reference a datasheet please specify which one and in which section (ie, the protocol manual, section 5.1.2). Additionally, screenshots are easy to paste into github.

I'm trying to use the NEO-M9N sparkfun breakout board with the STM32F103 working with arduino core. But the example Power Save Mode does not work. I looked at the M9N datasheet, and the library's command is slightly different. How Can I work around it?

I've tested the library with the same MCU with NEO-M8N and it works.

### Your workbench
* What development board or microcontroller are you using?

STM32F103

* What version of hardware or breakout board are you using? 

STM32F103 with NEO-m8n and NEO-M9N

* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

Use the NEO-M9N and try to use it in Power Save Mode.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by PaulZC** [comment]
Hi Caio (@caioorafael ),

Just a very quick answer. I will give you a more complete answer if you need it - let me know.

- Install [v3 of the GNSS Library](https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3)
- Look at the [VALSET examples](https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/blob/main/examples/VALGET_and_VALSET/Example2_SetVal/Example2_SetVal.ino)
- Use ```myGNSS.setVal8(UBLOX_CFG_PM_OPERATEMODE, 1);``` to set the power management operate mode: 0=FULL, 1=PSM On/Off, 2=PSM Cyclic Tracking
- Consult Section 5.9.16 of the [Interface Manual](https://www.u-blox.com/sites/default/files/u-blox-M9-SPG-4.04_InterfaceDescription_UBX-21022436.pdf) for more details
- The Configuration Keys you need are [here](https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/blob/957f1ac1a04108f580d50ca676ddfaaa6969b2d4/src/u-blox_config_keys.h#L975-L992)

Please re-open this if you need a more complete answer.

Best wishes,
Paul
