### ISSUE TITLE
Compatibility with arduino giga

### ISSUE THREAD

**Issue by Nocentinia** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#204]
Good morning,

I was wondering if this library was compatible with arduino Giga R1. I would like to communicate with GPS via UART

**Comment by PaulZC** [comment]
Hi,

I have not tried it, but, yes, it should work fine.

The GIGA R1 (WiFi) is a 3.3V board. It has plenty of RAM and four hardware UART ports.

I am not sure which Serial (UART) port you should use. For example, it looks like ```Serial2``` is connected to pins 18 (Tx) and 19 (Rx). If you use that port, you will need to change the ```begin``` to:

```
myGNSS.begin(Serial2)
```

Best wishes,
Paul
