### ISSUE TITLE
In getProtocolVersion(), PayloadCfg out of bounds

### ISSUE THREAD

**Issue by xuyaozhong** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#217]
Default sizeof payloadCfg is 256.  
Array 'payloadCfg[256]' **accessed at index 270, which is out of bounds.**
Please fix this issue.
Thank you

`diff --git a/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp b/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
index 6d68956..f2e51fc 100644
--- a/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
+++ b/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
@@ -7725,7 +7725,7 @@ bool SFE_UBLOX_GNSS::getProtocolVersion(uint16_t maxWait)
   // }

   // We will step through the payload looking at each extension field of 30 bytes
-  for (uint8_t extensionNumber = 0; extensionNumber < 10; extensionNumber++)
+  for (uint8_t extensionNumber = 0; extensionNumber < (packetCfgPayloadSize / 30); extensionNumber++)
   {
     // Now we need to find "PROTVER=18.00" in the incoming byte stream
     if ((payloadCfg[(30 * extensionNumber) + 0] == 'P') && (payloadCfg[(30 * extensionNumber) + 6] == 'R'))
`

**Comment by PaulZC** [comment]
Hi @xuyaozhong ,

Thank you for reporting this issue.

Which u-blox module are you using?

I can not replicate this issue with either the NEO-F10N or MAX-M10S. But I have corrected it in [v2.2.26](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/releases/tag/v2.2.26). Please test v2.2.26 with your module.

Best wishes,
Paul
