### ISSUE TITLE
pushRawData make input data const

### ISSUE THREAD

**Issue by dizcza** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#221]
The `pushRawData` function takes constant data buffer `dataBytes` and should help users with the `cost` modifier.

Now I need to cast my const data to `uint8_t*` just because your API requires so.

**Comment by PaulZC** [comment]
Hi Danylo (@dizcza ),

I agree, with hindsight, it would have been better to use the ```const``` modifier. But this would be a breaking change. I am not going to change it now.

Best wishes,
Paul
