### ISSUE TITLE
Controlling power completely with EXTINT

### ISSUE THREAD

**Issue by gauteh** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#228]
Hi,

it is currently possible to put the device to sleep with `powerOff`, this is a bit fragile since the device can easily be woken up again. It should be possible to configure the device to be completely controlled by the EXTINT pin: https://content.u-blox.com/sites/default/files/MAX-M10S_IntegrationManual_UBX-20053088.pdf (3.6.2.5 and 3.6.2.6). As far as I can see this is not currently possible with this driver. Would it be possible to implement this?

Best regards,
Gaute

**Comment by gauteh** [comment]
Hi, thank you! I was already using v3 (I got confused between the versions). I will try this, thank you very much!

**Comment by PaulZC** [comment]
No problem! I am closing this. If you need more help, please open a new issue in v3.

Best,
Paul
