### ISSUE TITLE
Best practices: Raw data logging rates

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#48]
Hi Paul,

Following-up on our conversation regarding best practices for changing the raw data logging rates, I wanted to share a couple of quick results from a logging test today.

### Test setup:
* MicroMod Data Logging Carrier Board
* MicroMod Artemis Processor
* SparkFun GPS-RTK-SMA Breakout - ZED-F9P
* 6600 mAh LiPo
* GNSS Multi-Band L1/L2 Surveying Antenna (TNC) - TOP106

### Configuration:
* Both systems are identically configured except for how the logging rates are set. 
* The code is custom but has the DataLoggingExample4 from the u-blox library at its core.
* Both tests were conducted at the exact same time and were run for 1 hour.
* Results screenshots below are taken from Emlid's new and very handy tool "Emlid Studio" for processing .ubx data, which runs RTKLIB under the hood. 

### Test 1: 
* Measurement and navigations rates set to one second

**Code:**
```
gnss.setNavigationFrequency(1);
```

**Results:**
* Very typical output for my location. 
* Several uninterrupted connections to GPS and GLONASS satellites. 
* Many L2 only signals.

![Screen Shot 2021-06-30 at 1 53 35 PM](https://user-images.githubusercontent.com/22924092/124008677-ad4b6800-d9aa-11eb-83e3-cd517860d10d.png)

### Test 2: 
* Measurement rate set to 1000 ms and navigation rate (ratio) set to 15.

**Code:**
```
gnss.setMeasurementRate(1000);  // Set the measurement rate to 1 second (1000 milliseconds)
gnss.setNavigationRate(15); // Set the navigation rate (ratio) to 15 to produce a solution every 15 s
```
**Results:**
* It's immediately clear that something is up.
* It appears that in many cases it was not possible for the receiver to achieve an L2 lock. 
* Many of the L2 only signals are also missing.
![Screen Shot 2021-06-30 at 12 20 07 PM](https://user-images.githubusercontent.com/22924092/124008687-b0deef00-d9aa-11eb-8c88-bde5df2fd49f.png)

## Discussion
* It's appears that L2 performance is severely degraded when increasing the navigation rate to 15. 
* I have tried difference combinations of receivers, processors and antennas to ensure that this isn't a hardware issue. 
* I'm currently waiting on the NRCan PPP outputs from the above two RINEX files. I'm very curious to see what the results will be.

I'll update this issue later on!

Cheers,
Adam

**Comment by adamgarbo** [comment]
**NRCan Ultra-rapid PPP results:**

Test | Latitude (+/- cm) | Longitude (+/- cm) | Height (+/- cm) |
-- | -- | -- | -- |
1 | 0.077 | 0.113 | 0.232
2 | 2.550 | 2.778 | 6.660

**Comment by adamgarbo** [comment]
Hi @PaulZC,

I have decided not to use the `.setMeasurementRate(1000)` and `.setNavigationRate(15)` functions for my current project, and instead switch back to `setNavigationFrequency(1)`, which we know works reliably. 

However, I'd still curious if you have any thoughts on what could be causing the large gaps in logged data. Could this be a bug?

Cheers,
Adam

**Comment by PaulZC** [comment]
I wonder if this is something to do with low power modes?
Are you changing the receiver management configuration (UBX_CFG_RXM)?
Maybe even with the default configuration, the modules tries to be clever and save power because it knows you only want an update every 15 seconds...?
I must admit I've only ever used ```setMeasurementRate``` and ```setNavigationRate``` to adjust 'normal' things like PVT. Maybe something strange happens when logging RAWX at such slow rates?
All the best,
Paul

**Comment by adamgarbo** [comment]
Hi Paul,

It could be a possibility that the receiver is trying to save power between measurements. The Interface Description does note for UBX-CFG-RATE:

> When using power save mode, measurement and navigation rate can differ from the values configured. 

It could be that a power-saving mode is enabled by default that I'm not aware of, which only activates with a sufficiently slow logging rate.

Regarding commands issued to the receiver, with the exception of `setAutoPVT()`, they are identical to the DataLoggingExample4. I also did a factory reset of the receiver to be sure. 

```
gnss.setI2COutput(COM_TYPE_UBX);                  // Set the I2C port to output UBX only (disable NMEA)
gnss.saveConfigSelective(VAL_CFG_SUBSEC_IOPORT);  // Save communications port settings to flash and BBR
gnss.setNavigationFrequency(1);                   // Produce one navigation solution per second
gnss.setAutoPVT(true);                            // Enable automatic NAV-PVT messages
gnss.setAutoRXMSFRBX(true, false);                // Enable automatic RXM-SFRBX messages
gnss.setAutoRXMRAWX(true, false);                 // Enable automatic RXM-RAWX messages
gnss.logRXMSFRBX();                               // Enable RXM-SFRBX data logging
gnss.logRXMRAWX();                                // Enable RXM-RAWX data logging
```

I'll try to look at the power save modes in more detail when I have some time. I'll keep this issue open for now in case other users may be looking to do something similar!

Cheers,
Adam

**Comment by PaulZC** [comment]
Many thanks Adam,
Paul

**Comment by adamgarbo** [comment]
Hi Paul,

I believe I'm finally ready to close this issue!

After sorting out the power issues (it seems the order in which you provide power to the MMDLCB/ZED-F9P when also connecting to serial via USB-C seems to be really finicky and I haven't 100% figured it out), I started to run some additional tests with various measurement and navigation rates. 

I'm happy to report that I did not experience the same issues as the original tests, where the receiver would seem to consistently lose its signal lock. I ran several tests and all were successful. Please see below for two examples, including the original test conditions.

### Test 1
```
gnss.setMeasurementRate(5000);  // Set the measurement rate to 5 seconds (5000 milliseconds)
gnss.setNavigationRate(1); // Set the navigation rate (ratio) to 1 to produce a solution every 5 s
```

![image](https://user-images.githubusercontent.com/22924092/139559173-0664e614-fe85-4e99-b4da-9a33447e4721.png)

### Test 2
```
gnss.setMeasurementRate(1000);  // Set the measurement rate to 1 second (1000 milliseconds)
gnss.setNavigationRate(15); // Set the navigation rate (ratio) to 15 to produce a solution every 15 s
```
![image](https://user-images.githubusercontent.com/22924092/139559176-e49b3f1c-bdb2-4e32-b7af-f89007c58549.png)

It's difficult to say what may have caused initial issue, but I'm glad that for now it seems to have been resolved. I'll close this issue for the time being but will certainly open it back up again if I encounter the same issue in future RAWX/SFRBX logging.

I've also been in touch with Clive from the u-blox Support portal and he's advised in terms of best practice, if for example I wanted to log RAWX data at 5 seconds, I should use a measurement rate of 5000 ms and a navigation rate of 1. He also wasn't fond of the idea of a 30 second logging interval for PPP post-processing, so I suspect for the foreseeable future I'll continue to log at 1 Hz.

Relevant question:
https://portal.u-blox.com/s/feed/0D52p0000BbvoEPCQY

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi Adam,

Thanks for the update. Glad that's working for you.

All the best,
Paul

**Comment by adamgarbo** [comment]
Hi Paul,

Rereading #70, do you think changes to UBX_RXM_RAWX_MAX_BLOCKS would have made a difference with the gaps in the data originally observed in this issue? With only GPS+GLONASS enabled, I doubt that I was ever pushing the limit, especially with a partially obstructed sky view.

Might have to chalk this one up to a random ephemeral bug! 

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi Adam,

You would only see data loss if the number of blocks in a single RAWX message exceeded UBX_RXM_RAWX_MAX_BLOCKS - originally 64, now 92. A useful question to answer is "with only GPS+GLONASS enabled, do the RAWX messages _only_ contain blocks from GPS+GLONASS"? I'll have a look at that when I get some free time. A simple test would be to run the UBX Integrity Checker on your data. It will report the longest UBX message payload length. If that is _close_ or _equal_ to 2064 bytes (16 + 32 * 64), then data loss might have happened.

Cheers,
Paul
