### ISSUE TITLE
Example2_NMEAParsking to big for Arduino Uno?

### ISSUE THREAD

**Issue by nabelekt** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#67]
I am yrying to compile and upload Example2_NMEAParsking for Arduino Uno R3. With versions of the library 2.0.13 and 2.0.15, I get, 

```
Sketch uses 33058 bytes (102%) of program storage space. Maximum is 32256 bytes.text section exceeds available space in board

Global variables use 953 bytes (46%) of dynamic memory, leaving 1095 bytes for local variables. Maximum is 2048 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
Error compiling for board Arduino Uno.
```

I know that I have done this before successfully (though, it was in the IDE v2 beta). Has something changed recently to make the sketch bigger?
I have MicroNMEA library version 2.0.5 installed. Arduino IDE version 1.8.16.

**Comment by PaulZC** [comment]
Hi Thomas (@nabelekt ),
The library has grown a lot in terms of its functionality. We've tried to keep the code size as small as possible but, yes, we're now at the tipping point on processors like the ATmega328P. You can delete some of the debug messages to save code space. Please see [these notes](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#memory-usage) for more details.
Best wishes,
Paul
