### ISSUE TITLE
RAWX data gaps in RINEX file (logging issue)

### ISSUE THREAD

**Issue by derekpickell** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#70]
### Subject of the issue
Using the example data logging RAWX/SFRBX (both versions w/ and w/out callbacks), and without changing the Navigational Frequency (1Hz), the processed RINEX file contains data gaps of random intervals (sometimes 3+ seconds). This is also reflected in the serial monitor when the numRAWX counter occasionally hangs up on a single count for several iterations. 

I cut the I2C bridges on both MicroMod and peripheral without any change in performance. There doesn't seem to be any issues with the buffers overflowing, and also no improvement in output consistency when I disable SFRBX messages to try to decrease the message load. 

### Setup
MicroMod Data Logging Carrier Board
MicroMod Artemis Processor
SparkFun GPS-RTK-SMA Breakout - ZED-F9P
UBLOX L1/L2 Antenna
Formatted SanDisk 4GB microsd

### Configuration
Attempted using DataLoggingExample3_RXM_SFRBX_and_RAWX and version without callbacks. (Only change was CS needed to be changed to pin 41). Hooked up exactly per instructions with Qwiic connector. 

Processed raw .ubx data using RTKLIB and UNAVCO teqc, both outputting RINEX files that come with GNSS data gaps. 

As a sanity check, I used Ucenter to log Raw .ubx data, and the sampling interval is consistent. Could this be an issue with the SD card? I see no indication from the buffers that it is getting hung up enough to drop data. Also tried slowing setMeasurementRate() to 10 second intervals, which still have data gaps. Unsure what other root cause it could be at this point... Appreciate the help! First time posting something here. 

Snippet from RINEX file: Note in red how the subsequent GNSS data timestamp indicates it arrived 2 seconds after the first. 
<img width="576" alt="Screen Shot 2021-10-13 at 3 04 34 PM" src="https://user-images.githubusercontent.com/37055625/137197335-9424bcb9-96dc-4af7-b6e8-c141e2f63228.png">

Serial monitor:
<img width="399" alt="Screen Shot 2021-10-13 at 2 59 47 PM" src="https://user-images.githubusercontent.com/37055625/137196667-89f929bd-f12f-40c7-9f4a-fe6cba09b0c0.png">

### EDIT: 
After enabling debug messages, following message occurs during hiccups: "insufficient space available! Data will be lost!". This is surprising to me because the fileBufferSize doesn't approach full. Could the write to SD be hanging up the rest of the program? 
<img width="644" alt="Screen Shot 2021-10-14 at 8 59 42 AM" src="https://user-images.githubusercontent.com/37055625/137341294-39348b33-0a28-4ba9-9639-e5b17d156db8.png">

And checksum failed (lower level debugging enabled):
<img width="724" alt="Screen Shot 2021-10-14 at 8 53 15 AM" src="https://user-images.githubusercontent.com/37055625/137341318-957e75cf-1edd-4377-a371-e15c4f52ce94.png">

**Comment by derekpickell** [comment]
Hi @PaulZC, 

I've been running on v2.1.0, so haven't had any luck there. So I guess the next thing to try is disabling the internal I2C pull-ups in the Artemis. Let me know the best way to go about this (I assume this has to do with Wire.setPullups(0); but when I move this statement outside of the #if defined() I get the following error: 'class arduino::MbedI2C' has no member named 'setPullups'. 

Appreciate the help!

**Comment by derekpickell** [comment]
Hi @PaulZC 

Thank you again for all the help. I've been running with your suggested code update for the last 24 hours, and no more "Checksum Failed" error--1Hz RAWX is nearly perfect. However, the following still occurs, albeit very infrequently that still results in the occasional data gap:

 "processUBX: buffer overrun detected! activePacketBuffer: 3 maximum_payload_size: 2064
process: memory is already allocated for payloadAuto! Deleting.."

I've updated the to v2.0.16 just now and still seeing this particular problem pop up every 30 minutes of logging or so. Not sure if it's related to i2c communication or not but looking into this issue now.

**Comment by PaulZC** [comment]
Regarding the 0.979 second sample spacing, was that two single instances? Or two 'groups' or instances?

If it was two single instances, I suspect that was probably due to the module refining its lock on GNSS time? I don't think that's anything to worry about, but thank you for mentioning it.

**Comment by PaulZC** [comment]
Closed by v2.0.17
