### ISSUE TITLE
[Feature Request] : script to repair UBX files

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#71]
Sometime, the Sparkfun Express is producing slightly corrupted files : [https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/49](url)

Similar to the UBX_Integrity_Checker script, I would appreciate a script that can repair damaged files i.e. that remove incorrect sentences.

**Comment by Eric-FR** [comment]
Yes, of course, it can be done with Python. I did a try on your Checker two days and it was successful. It confirmed me that there was some corrupted sentences ;-).

**Comment by PaulZC** [comment]
Hi Eric (@Eric-FR ),

Please try [this version of the integrity checker](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/release_candidate/Utils/UBX_Integrity_Checker.py). Please let me know if it repairs your files correctly. If it works for you, I will merge it into the main branch of the library.

Very best wishes,
Paul
