### ISSUE TITLE
no data for ZED F9P

### ISSUE THREAD

**Issue by nur921606** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#72]
Hello. I have questions to ask. I'm using one of the sparkfun electronic device which is RTK-GNSS ZED-F9P module. To run the module with arduino IDE, do I have to use the ZED-F9P module with the RedBoard Artemis? because I try to run one of the RTK-GNSS sparkfun arduino library (get the high precision geodetic solution for latitude and longitude using double) with the ZED-F9P board module only. but I'm not received any data from that module.

**Comment by PaulZC** [comment]
Hello @nur921606 ,

The [GPS Forum](https://forum.sparkfun.com/viewforum.php?f=116) is a good place to ask questions about how to use our GNSS boards.

Please have a look at the [hook-up guide for the ZED-F9P](https://learn.sparkfun.com/tutorials/gps-rtk2-hookup-guide?_ga=2.235090817.1011208615.1634383213-1372054063.1597140555#sparkfun-u-blox-arduino-library). Yes, you do need to run the u-blox library code on one of our RedBoards. The RedBoard Artemis is a good choice as it has plenty of memory. I can also recommend our ESP32 boards - some of which come with a [microSD socket for data logging](https://www.sparkfun.com/products/18018).

You can also use u-blox's u-center software and connect via USB-C - without a RedBoard.

Best wishes,
Paul
