### ISSUE TITLE
[Example15_NTRIPClient] NTRIP Trimble Ntrip Caster 4.3 needs additional headers

### ISSUE THREAD

**Issue by SunboX** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#83]
### Subject of the issue

The NTRIP Caster I like to use needs additional headers, otherwise it will not respond anything.

This is the caster: http://www.ntrip.sachsen.de/
```
SOURCETABLE 200 OK
Server: NTRIP Trimble Ntrip Caster 4.3
Content-Type: text/plain
Content-Length: 2890
Date: Wed, 01 Dec 2021 13:00:36 UTC

STR;0157_MSM;0157_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0132_MSM;0132_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0133_MSM;0133_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0136_MSM;0136_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0139_MSM;0139_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0140_MSM;0140_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0142_MSM;0142_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0143_MSM;0143_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0148_MSM;0148_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0149_MSM;0149_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0151_MSM;0151_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0153_MSM;0153_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0154_MSM;0154_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0156_MSM;0156_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0144_MSM;0144_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble NetR9;none;B;Y;9600;;
STR;0161_MSM;0161_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble Alloy;none;B;Y;9600;;
STR;0162_MSM;0162_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble Alloy;none;B;Y;9600;;
STR;0163_MSM;0163_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble Alloy;none;B;Y;9600;;
STR;0164_MSM;0164_MSM;RTCM 3.2;1006 (10),1008 (10), 1013 (60), 1033 (10);;2;GPS+GLO+GAL+BDS;SAPOS;DEU;0;0;0;0;Trimble Alloy;none;B;Y;9600;;
CAS;31.12.57.11;80;SAPOS-SN;SAPOS-SN;0;DEU;0;0;0.0.0.0;0;4;
NET;SAPOS_SN;GEOSN;B;Y;http://www.landesvermessung.sachsen.de;http://www.landesvermessung.sachsen.de;mailto:sapos@geosn.sachsen.de;;
ENDSOURCETABLE
```

With those changes to the sample code / headers, it does repsond:
```c++
snprintf(
    serverRequest, 
    SERVER_BUFFER_SIZE, 
    "GET /%s HTTP/1.0\r\nUser-Agent: NTRIP TestClient/1.0\r\nNtrip-Version: Ntrip/2.0\r\nNtrip-GGA: %s\r\n",
    mountpoint,
    "$GPGGA,082513.662,5029.847,N,01208.323,E,1,12,1.0,0.0,M,0.0,M,,*6D"
);
```
Also as far as I know, the User-Agent header must have a specific format regarding to the NTRIP definition.

![NTRIP](https://user-images.githubusercontent.com/83344/144239493-1915ee67-9ee5-4091-aa95-2e1ad79aac67.PNG)

I'm running it on a TTGO-T-Call board using the TinyGSM@^0.10.9 client. Project is set up and compiled in PlatformIO.

/cc @nseidle

**Comment by SunboX** [comment]
Here's some more information about the User-Agent format: https://www.use-snip.com/kb/knowledge-base/ntrip-rev1-versus-rev2-formats/

**Comment by nseidle** [comment]
Hi SunboX - thanks for reporting! I'll try to get this fixed shortly.

**Comment by jkreienh** [comment]
I'm getting what I think might be a similar issue with Example14_NTRIPServer.ino

![image](https://user-images.githubusercontent.com/34135562/145659741-073e0a45-4bf8-40ca-b889-d0c53a5c43b4.png)

**Comment by SunboX** [comment]
@jkreienh Are you sure? 401 Unauthorized normally points to wrong credentials.

**Comment by jkreienh** [comment]
@SunboX

Well, I can get it working via RTKLIB and STRSVR with the same credentials to what I've set in secrets.h and verified via the serial console.  I'm just wondering if the SOURCE string now needs to be Base64 encoded or something or if they changed something in the escape characters.

**Comment by nseidle** [comment]
@jkreienh - I suspect you have a different issue and it is related to an [RTK Surveyor](https://github.com/sparkfun/SparkFun_RTK_Firmware) because your Agent is "SparkFun_RTK_Surveyor". Please consider posting an issue on that repo.

Your credentials do indeed look bad. The "Sending credentials" line will show something. For example, example 15 does this:

![image](https://user-images.githubusercontent.com/117102/145728184-59b31ff5-6526-49bc-b1a0-d5861760b956.png)

FYI/Note: RTK2Go is, any day now, going to start requiring an email address for a user name.
![image](https://user-images.githubusercontent.com/117102/145728244-a13d7c83-8521-483a-b7b5-9700f6d0a671.png)

**Comment by nseidle** [comment]
@SunboX - I've added [example 16](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/AddGPGGAToNTRIP/examples/ZED-F9P/Example16_NTRIPClient_WithGGA/Example16_NTRIPClient_WithGGA.ino) ready for your testing. I am not confident it will fix your issue but it *is* parsing the current GGA and passing it every 10 seconds.

![image](https://user-images.githubusercontent.com/117102/145729210-d508a331-d37e-4e41-8067-da97f7b1252c.png)

If you can direct me how to apply for credentials for the ntrip.sachsen.de server, that would be helpful.

If you have any feedback on the example, please share. I'm sure it could be made better and more utilitarian.

**Comment by nseidle** [comment]
Ugh Sorry @jkreienh. Example 14 works very differently than 15/16 and the credentials are not shown on that line. I'll open an issue for you. Please continue [over there](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/issues/91).

**Comment by SunboX** [comment]
hey @nseidle , thank you very much! I will test your example.

Getting credentials for the NTRIP server of the land survey of the federal state of Saxony is pretty easy and for free, but you have to fill out this German form (I'm not aware of an english version of it): https://fs.egov.sachsen.de/formserv/findform?shortname=smi_geosn-303&formtecid=11&areashortname=SMI_LVA

Then you will get your credentials via email. 

But in the meanwhile, I will send you mine for temporary use. But please do not publish them. ;)
