### ISSUE TITLE
Problems with Ex14 NTRIP Caster Unauthorized 

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#91]
Moved from issue [83](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/issues/83).

Problem getting ex 14 working with rtk2go:

![image](https://user-images.githubusercontent.com/34135562/145659741-073e0a45-4bf8-40ca-b889-d0c53a5c43b4.png)

Unauthorized access error from RTK2go.

**Comment by nseidle** [comment]
The 'SparkFun_RTK_Surveyor' is a hold over from the RTK project and will be corrected.

I cannot replicate the problem right now.

![image](https://user-images.githubusercontent.com/117102/145729905-0215bce3-7d35-4c90-8193-352bbca0c167.png)

Using our dummy credentials can you connect successfully?

**Comment by nseidle** [comment]
Perhaps you're using a caster that does not allow open casters. SNIP has a [good explanation](https://www.use-snip.com/kb/knowledge-base/pre-ntrip-client-connections/). Base64 would then indeed be needed. Let me see if I can replicate your error on Emlid (closed casting).

**Comment by jkreienh** [comment]
@nseidle I think I've got it working.  Somehow I got the Pw and MtPnt backward during all my troubleshooting. 

http://rtk2go.com:2101/SNIP::MOUNTPT?NAME=AUS_TX

**Comment by nseidle** [comment]
Good to know! Glad you got it working.
