### ISSUE TITLE
Suddenly started getting "data was NOTACKNOWLEDGED (NACK) after 23 msec"

### ISSUE THREAD

**Issue by ricozinn** [sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#98]
Hi, I have board Artemis OpenLog board connected to the NEO-MN9 breakout board (https://www.sparkfun.com/products/15712) running version 2.0.15 of this library.  I was testing for hours with no problem and then I started getting this below.  Nothing had changed in software so I was suspecting some hardware damage, but under a microscope I can't see any signs of any kind of issue anywhere (not on the PCB nor on the external enclosure it was in protecting it).  Does anyone have an idea of where I should take a closer look?  The below is what I get when I issue any command, but this one in particular is trying to set dynamic mode to automotive:
`sensor->setDynamicModel(DYN_MODEL_AUTOMOTIVE)`

Also, even while this is happening the PPS LED is flashing meaning I think I've got a GPS fix, but I can't get any of the data or issue any commands.  Looking at the debug logging below though it looks like part of the response is received, so it makes me think it isn't just the I2C/QWIIC connection that is failing but possibly something deeper.  Anyway, hoping someone with some experience has an idea of what's going on and can point me in the right direction.

I can swap the GNSS breakout board to another spare I have here and the problem goes away, so I am confident it is a problem on the GNSS breakout board side.

10:11:03.516 -> Sending: CLS:CFG ID:0x24 Len: 0x0 Payload:
10:11:03.516 -> sendCommand: Waiting for ACK response
10:11:03.516 -> checkUbloxI2C: Large packet of 154 bytes received
10:11:03.516 -> process: incoming "automatic" message: Class: 0x1 ID: 0x7
10:11:03.550 -> Checksum failed: checksumA: 53 checksumB: 91 rollingChecksumA: 181 rollingChecksumB: 91
10:11:03.550 -> Incoming: Size: 36 Received: CLS:CFG ID:0x24 Len: 0x24 Payload: FF FF 0 3 0 0 0 0 10 27 0 0 5 0 FA 0 FA 0 64 0 5E 1 0 3C 0 0 0 0 0 0 0 0 0 0 0 0
10:11:03.550 -> packetCfg now valid
10:11:03.550 -> packetCfg classAndIDmatch
10:11:03.550 -> Incoming: Size: 2 Received: CLS:ACK ID:0x1 Len: 0x2 Payload: 6 24
10:11:03.550 -> packetCfg now valid
10:11:03.550 -> packetAck now valid
10:11:03.550 -> packetCfg classAndIDmatch
10:11:03.550 -> packetAck classAndIDmatch
10:11:03.550 -> waitForACKResponse: valid data and valid ACK received after 32 msec
10:11:03.550 -> 
10:11:03.550 -> Sending: CLS:CFG ID:0x24 Len: 0x24 Payload: 1 0 4 3 0 0 0 0 10 27 0 0 5 0 FA 0 FA 0 64 0 5E 1 0 3C 0 0 0 0 0 0 0 0 0 0 0 0
10:11:03.550 -> sendCommand: Waiting for ACK response
10:11:03.550 -> checkUbloxI2C: Large packet of 138 bytes received
10:11:03.550 -> processUBX: NACK received: Requested Class: 0x6 Requested ID: 0x24
10:11:03.583 -> Incoming: Size: 2 Received: CLS:ACK ID:0x0 Len: 0x2 Payload: 6 24
10:11:03.583 -> packetCfg now valid
10:11:03.583 -> packetAck now valid
10:11:03.583 -> waitForACKResponse: data was NOTACKNOWLEDGED (NACK) after 23 msec

**Comment by PaulZC** [comment]
Hi Richard (@ricozinn ),

I suspect this is pull-up related - and not an issue with the library. Let’s continue the discussion on the Forum, not here.

Best wishes,
Paul
